# Generated by Django 3.2.12 on 2022-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('yearly_change', models.FloatField()),
                ('net_change', models.IntegerField()),
                ('density', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('migrants', models.IntegerField()),
                ('fert_rate', models.FloatField()),
                ('med_age', models.IntegerField()),
                ('urban_pop', models.IntegerField()),
                ('world_share', models.FloatField()),
            ],
            options={
                'ordering': ['country'],
            },
        ),
    ]
